trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- script: terraform --version
  displayName: 'Check Terraform Version'

- script: terraform init
  displayName: 'Terraform Init'
  workingDirectory: 'parent_module'

- script: terraform validate
  displayName: 'Terraform Validate'
  workingDirectory: 'parent_module'

- script: terraform plan
  displayName: 'Terraform Plan'
  workingDirectory: 'parent_module'