title = "DevOpsInsiders Gitleaks Configuration"

[allowlist]
description = "Ignore Terraform state files and cache"

paths = [
  '''\.terraform/''',
  '''\.terraform\.lock\.hcl''',
  '''terraform\.tfstate''',
  '''terraform\.tfstate\.backup''',
  '''checkov-report\.json''',
  '''checkov-report\.txt'''
]