trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.13.1'

steps:
- checkout: self

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: $(terraformVersion)

- script: terraform version
  displayName: Terraform Version

- script: terraform init
  workingDirectory: parent_module
  displayName: Terraform Init

- script: terraform fmt -check
  workingDirectory: parent_module
  displayName: Terraform Format Check

- script: terraform validate
  workingDirectory: parent_module
  displayName: Terraform Validate