trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.13.1'

steps:

- checkout: self

# Install Terraform
- script: |
    wget https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
    unzip terraform_1.13.1_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: 'Install Terraform'

# Verify Version
- script: terraform version
  displayName: 'Terraform Version'

# Terraform Init
- script: terraform init
  workingDirectory: parent_module
  displayName: 'Terraform Init'

# Terraform Format Check
- script: terraform fmt -check
  workingDirectory: parent_module
  displayName: 'Terraform Format Check'

# Terraform Validate
- script: terraform validate
  workingDirectory: parent_module
  displayName: 'Terraform Validate'
  - script: |
    curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    tflint --version
  displayName: Install TFLint

- script: |
    tflint --init
    tflint
  workingDirectory: parent_module
  displayName: Run TFLintgit
  - script: |
    python3 -m pip install --upgrade pip
    pip3 install checkov
    checkov --version
  displayName: 'Install Checkov'

- script: |
    checkov -d .
  workingDirectory: parent_module
  displayName: 'Run Checkov'
  - script: |
    checkov -d . -o cli -o junitxml --output-file-path console,checkov-report.xml
  workingDirectory: parent_module
  displayName: 'Run Checkov'
  - task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/checkov-report.xml'
    testRunTitle: 'Checkov Security Scan'
  condition: always()
  - script: |
    sudo apt-get update
    sudo apt-get install wget apt-transport-https gnupg lsb-release -y

    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
      gpg --dearmor | \
      sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

    echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
      sudo tee /etc/apt/sources.list.d/trivy.list

    sudo apt-get update
    sudo apt-get install trivy -y

    trivy --version
  displayName: 'Install Trivy'
  - script: |
    trivy config .
  workingDirectory: parent_module
  displayName: 'Run Trivy'
  - script: |
    wget https://github.com/gitleaks/gitleaks/releases/download/v8.24.2/gitleaks_8.24.2_linux_x64.tar.gz
    tar -xzf gitleaks_8.24.2_linux_x64.tar.gz
    sudo mv gitleaks /usr/local/bin/
    gitleaks version
  displayName: 'Install Gitleaks'
  - script: |
    gitleaks detect --source . --verbose
  workingDirectory: parent_module
  displayName: 'Run Gitleaks'