trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.13.1'

steps:

- checkout: self

# Install Terraform
- script: |
    wget https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
    unzip terraform_1.13.1_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: 'Install Terraform'

# Verify Version
- script: terraform version
  displayName: 'Terraform Version'

# Terraform Init
- script: terraform init
  workingDirectory: parent_module
  displayName: 'Terraform Init'

# Terraform Format Check
- script: terraform fmt -check
  workingDirectory: parent_module
  displayName: 'Terraform Format Check'

# Terraform Validate
- script: terraform validate
  workingDirectory: parent_module
  displayName: 'Terraform Validate'
  - script: |
    curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    tflint --version
  displayName: Install TFLint

- script: |
    tflint --init
    tflint
  workingDirectory: parent_module
  displayName: Run TFLintgit