name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Show Runner
        run: hostname
